PERL_EXPORTER_TINY_VERSION = 1.000000
PERL_EXPORTER_TINY_SOURCE = Exporter-Tiny-$(PERL_EXPORTER_TINY_VERSION).tar.gz
PERL_EXPORTER_TINY_SITE = http://search.cpan.org/CPAN/authors/id/T/TO/TOBYINK
PERL_EXPORTER_TINY_LICENSE = Artistic or GPL-1.0+
PERL_EXPORTER_TINY_LICENSE_FILES = LICENSE

$(eval $(perl-package))
