#!/bin/sh
#
# openil-init        Starts openil-init.
#

start() {
	printf "Starting openil-init: "
	/sbin/resize2fs /dev/disk/by-label/root 1>/dev/null 2>&1
	echo "OK"
}
stop() {
	printf "Stopping openil-init: "
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
exit $?
