NETOPEER2_KEYSTORED_VERSION = 0.7-r2
NETOPEER2_KEYSTORED_SITE = $(call github,CESNET,Netopeer2,v$(NETOPEER2_KEYSTORED_VERSION))
#NETOPEER2_KEYSTORED_SITE_METHOD = git
NETOPEER2_KEYSTORED_SUBDIR = keystored
NETOPEER2_KEYSTORED_INSTALL_STAGING = NO
NETOPEER2_KEYSTORED_LICENSE = BSD-3c
NETOPEER2_KEYSTORED_LICENSE_FILES = LICENSE
NETOPEER2_KEYSTORED_DEPENDENCIES = openssl sysrepo
NETOPEER2_KEYSTORED_MAKE_ENV += LD_LIBRARY_PATH+=$(HOST_DIR)/usr/lib

# prevent an attempted chown to root:root
NETOPEER2_KEYSTORED_CONF_OPTS += -DSYSREPOCTL_ROOT_PERMS="-p 666"
# we are responsible for providing a PEM file at /etc/keystored/keys/ssh_host_rsa_key.pem
NETOPEER2_KEYSTORED_CONF_OPTS += -DKEYSTORED_DEFER_SSH_KEY=ON

define NETOPEER2_KEYSTORED_INSTALL_DAEMON_SCRIPT
	$(INSTALL) -D -m 0751 package/netopeer2-keystored/S80netopeer2-keystored \
		$(TARGET_DIR)/etc/init.d/
endef

NETOPEER2_KEYSTORED_POST_INSTALL_TARGET_HOOKS = NETOPEER2_KEYSTORED_INSTALL_DAEMON_SCRIPT

$(eval $(cmake-package))
