#! /bin/sh
#
# sysv-rc postrm
#

set -e

case "$1" in
	remove) : ;;
	purge)
	    if [ -e /usr/share/debconf/confmodule ]; then
		. /usr/share/debconf/confmodule
		db_purge
	    fi
	    exit 0
	    ;;
	*) exit 0 ;;
esac

umask 022

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
